[pcep]
  listen_addr = "0.0.0.0"
  listen_port = "4189"
  keepalive = 30

[grpcapi]
  listen_addr = "0.0.0.0"
  listen_port = "12345"
  tokens = [""]  

[restapi]
  listen_addr = "0.0.0.0"
  listen_port = "1443"
  cert_file = ""
  key_file = ""
  user = ""
  pass = ""
  debug = false

[bgpls]
  as = 65001
  router_id = "19.19.19.19"

[log]
  text_format = false
  time_format = "2006-01-02T15:04:05.999999999Z07:00"
  full_timestamp = true
  disable_colors = false
  level = 5