[pcep]
  listen_addr = "192.168.1.14"
  listen_port = "4189"
  keepalive = 30
  pcc_clients = ["10.0.0.10","10.0.0.11"]  

[grpcapi]
  listen_addr = "127.0.0.1"
  listen_port = "12345"
  tokens = ["boom"]  

[restapi]
  listen_addr = "127.0.0.1"
  listen_port = "1443"
  certf_ile = ""
  key_file = ""

[log]
  text_format = true
  time_format = "2006-01-02T15:04:05.999999999Z07:00"
  full_timestamp = true
  disable_colors = false
  level = 5