---
mgmt_ip: 10.0.0.10
mgmt_if_name: fxp0
mgmt_dsc: "management interface into the cloud"
igp_loopback_ip: 10.10.10.10
iso_address: 49.0002.0100.1001.0010.00
model: vmx
autonomous_system: 65000
rr_role: client
lab: True
bgpls: True
segment_ipv4_index: 2010

loopback_interfaces:
  - name: lo0
    unit: 1
    ipv4_addr: 10.0.0.1/32

igp_interfaces:
  - name: ge-0/0/0
    unit: 0
    ipv4_addr: 10.1.0.1/31
    dsc: "vmxr1 ge-0/0/0"

  - name: ge-0/0/1
    unit: 0
    ipv4_addr: 10.1.0.2/31
    dsc: "vmxr3 ge-0/0/1"
