// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pceapi.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StopBGPRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopBGPRequest) Reset()         { *m = StopBGPRequest{} }
func (m *StopBGPRequest) String() string { return proto.CompactTextString(m) }
func (*StopBGPRequest) ProtoMessage()    {}
func (*StopBGPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_614bac86d996c9a3, []int{0}
}
func (m *StopBGPRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StopBGPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StopBGPRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StopBGPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopBGPRequest.Merge(m, src)
}
func (m *StopBGPRequest) XXX_Size() int {
	return m.Size()
}
func (m *StopBGPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopBGPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopBGPRequest proto.InternalMessageInfo

type StopBGPReplay struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopBGPReplay) Reset()         { *m = StopBGPReplay{} }
func (m *StopBGPReplay) String() string { return proto.CompactTextString(m) }
func (*StopBGPReplay) ProtoMessage()    {}
func (*StopBGPReplay) Descriptor() ([]byte, []int) {
	return fileDescriptor_614bac86d996c9a3, []int{1}
}
func (m *StopBGPReplay) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StopBGPReplay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StopBGPReplay.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StopBGPReplay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopBGPReplay.Merge(m, src)
}
func (m *StopBGPReplay) XXX_Size() int {
	return m.Size()
}
func (m *StopBGPReplay) XXX_DiscardUnknown() {
	xxx_messageInfo_StopBGPReplay.DiscardUnknown(m)
}

var xxx_messageInfo_StopBGPReplay proto.InternalMessageInfo

type SessionsRequest struct {
	PccName              string   `protobuf:"bytes,1,opt,name=pccName,proto3" json:"pccName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionsRequest) Reset()         { *m = SessionsRequest{} }
func (m *SessionsRequest) String() string { return proto.CompactTextString(m) }
func (*SessionsRequest) ProtoMessage()    {}
func (*SessionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_614bac86d996c9a3, []int{2}
}
func (m *SessionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SessionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SessionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SessionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionsRequest.Merge(m, src)
}
func (m *SessionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *SessionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionsRequest proto.InternalMessageInfo

func (m *SessionsRequest) GetPccName() string {
	if m != nil {
		return m.PccName
	}
	return ""
}

type Session struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MsgCount             uint64   `protobuf:"varint,2,opt,name=MsgCount,proto3" json:"MsgCount,omitempty"`
	State                int32    `protobuf:"varint,3,opt,name=State,proto3" json:"State,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Keepalive            uint32   `protobuf:"varint,5,opt,name=Keepalive,proto3" json:"Keepalive,omitempty"`
	DeadTimer            uint32   `protobuf:"varint,6,opt,name=DeadTimer,proto3" json:"DeadTimer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_614bac86d996c9a3, []int{3}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Session.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return m.Size()
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Session) GetMsgCount() uint64 {
	if m != nil {
		return m.MsgCount
	}
	return 0
}

func (m *Session) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Session) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Session) GetKeepalive() uint32 {
	if m != nil {
		return m.Keepalive
	}
	return 0
}

func (m *Session) GetDeadTimer() uint32 {
	if m != nil {
		return m.DeadTimer
	}
	return 0
}

type SessionsReply struct {
	Sessions             []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SessionsReply) Reset()         { *m = SessionsReply{} }
func (m *SessionsReply) String() string { return proto.CompactTextString(m) }
func (*SessionsReply) ProtoMessage()    {}
func (*SessionsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_614bac86d996c9a3, []int{4}
}
func (m *SessionsReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SessionsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SessionsReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SessionsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionsReply.Merge(m, src)
}
func (m *SessionsReply) XXX_Size() int {
	return m.Size()
}
func (m *SessionsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionsReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionsReply proto.InternalMessageInfo

func (m *SessionsReply) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type LSPRequest struct {
	PccName              string   `protobuf:"bytes,1,opt,name=pccName,proto3" json:"pccName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LSPRequest) Reset()         { *m = LSPRequest{} }
func (m *LSPRequest) String() string { return proto.CompactTextString(m) }
func (*LSPRequest) ProtoMessage()    {}
func (*LSPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_614bac86d996c9a3, []int{5}
}
func (m *LSPRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LSPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LSPRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LSPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LSPRequest.Merge(m, src)
}
func (m *LSPRequest) XXX_Size() int {
	return m.Size()
}
func (m *LSPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LSPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LSPRequest proto.InternalMessageInfo

func (m *LSPRequest) GetPccName() string {
	if m != nil {
		return m.PccName
	}
	return ""
}

type LSP struct {
	Delegate bool   `protobuf:"varint,1,opt,name=Delegate,proto3" json:"Delegate,omitempty"`
	Sync     bool   `protobuf:"varint,2,opt,name=Sync,proto3" json:"Sync,omitempty"`
	Remove   bool   `protobuf:"varint,3,opt,name=Remove,proto3" json:"Remove,omitempty"`
	Admin    bool   `protobuf:"varint,4,opt,name=Admin,proto3" json:"Admin,omitempty"`
	Oper     uint32 `protobuf:"varint,5,opt,name=Oper,proto3" json:"Oper,omitempty"`
	Name     string `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	Src      string `protobuf:"bytes,7,opt,name=Src,proto3" json:"Src,omitempty"`
	Dst      string `protobuf:"bytes,8,opt,name=Dst,proto3" json:"Dst,omitempty"`
	// EROList      []EROSub
	// SREROList    []*SREROSub
	// SRRROList    []*SRRROSub
	SetupPrio    uint32 `protobuf:"varint,9,opt,name=SetupPrio,proto3" json:"SetupPrio,omitempty"`
	HoldPrio     uint32 `protobuf:"varint,10,opt,name=HoldPrio,proto3" json:"HoldPrio,omitempty"`
	LocalProtect bool   `protobuf:"varint,11,opt,name=LocalProtect,proto3" json:"LocalProtect,omitempty"`
	BW           uint32 `protobuf:"varint,12,opt,name=BW,proto3" json:"BW,omitempty"`
	PLSPID       uint32 `protobuf:"varint,13,opt,name=PLSPID,proto3" json:"PLSPID,omitempty"`
	LSPID        uint32 `protobuf:"varint,14,opt,name=LSPID,proto3" json:"LSPID,omitempty"`
	// IPv4ID       *LSPIPv4Identifiers
	// IPv6ID       *LSPIPv6Identifiers
	SRPID                uint32   `protobuf:"varint,15,opt,name=SRPID,proto3" json:"SRPID,omitempty"`
	ExcludeAny           uint32   `protobuf:"varint,16,opt,name=ExcludeAny,proto3" json:"ExcludeAny,omitempty"`
	IncludeAny           uint32   `protobuf:"varint,17,opt,name=IncludeAny,proto3" json:"IncludeAny,omitempty"`
	IncludeAll           uint32   `protobuf:"varint,18,opt,name=IncludeAll,proto3" json:"IncludeAll,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LSP) Reset()         { *m = LSP{} }
func (m *LSP) String() string { return proto.CompactTextString(m) }
func (*LSP) ProtoMessage()    {}
func (*LSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_614bac86d996c9a3, []int{6}
}
func (m *LSP) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LSP.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LSP.Merge(m, src)
}
func (m *LSP) XXX_Size() int {
	return m.Size()
}
func (m *LSP) XXX_DiscardUnknown() {
	xxx_messageInfo_LSP.DiscardUnknown(m)
}

var xxx_messageInfo_LSP proto.InternalMessageInfo

func (m *LSP) GetDelegate() bool {
	if m != nil {
		return m.Delegate
	}
	return false
}

func (m *LSP) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

func (m *LSP) GetRemove() bool {
	if m != nil {
		return m.Remove
	}
	return false
}

func (m *LSP) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *LSP) GetOper() uint32 {
	if m != nil {
		return m.Oper
	}
	return 0
}

func (m *LSP) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LSP) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *LSP) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

func (m *LSP) GetSetupPrio() uint32 {
	if m != nil {
		return m.SetupPrio
	}
	return 0
}

func (m *LSP) GetHoldPrio() uint32 {
	if m != nil {
		return m.HoldPrio
	}
	return 0
}

func (m *LSP) GetLocalProtect() bool {
	if m != nil {
		return m.LocalProtect
	}
	return false
}

func (m *LSP) GetBW() uint32 {
	if m != nil {
		return m.BW
	}
	return 0
}

func (m *LSP) GetPLSPID() uint32 {
	if m != nil {
		return m.PLSPID
	}
	return 0
}

func (m *LSP) GetLSPID() uint32 {
	if m != nil {
		return m.LSPID
	}
	return 0
}

func (m *LSP) GetSRPID() uint32 {
	if m != nil {
		return m.SRPID
	}
	return 0
}

func (m *LSP) GetExcludeAny() uint32 {
	if m != nil {
		return m.ExcludeAny
	}
	return 0
}

func (m *LSP) GetIncludeAny() uint32 {
	if m != nil {
		return m.IncludeAny
	}
	return 0
}

func (m *LSP) GetIncludeAll() uint32 {
	if m != nil {
		return m.IncludeAll
	}
	return 0
}

type LSPReply struct {
	LSPs                 []*LSP   `protobuf:"bytes,1,rep,name=LSPs,proto3" json:"LSPs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LSPReply) Reset()         { *m = LSPReply{} }
func (m *LSPReply) String() string { return proto.CompactTextString(m) }
func (*LSPReply) ProtoMessage()    {}
func (*LSPReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_614bac86d996c9a3, []int{7}
}
func (m *LSPReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LSPReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LSPReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LSPReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LSPReply.Merge(m, src)
}
func (m *LSPReply) XXX_Size() int {
	return m.Size()
}
func (m *LSPReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LSPReply.DiscardUnknown(m)
}

var xxx_messageInfo_LSPReply proto.InternalMessageInfo

func (m *LSPReply) GetLSPs() []*LSP {
	if m != nil {
		return m.LSPs
	}
	return nil
}

func init() {
	proto.RegisterType((*StopBGPRequest)(nil), "pceapiproto.StopBGPRequest")
	proto.RegisterType((*StopBGPReplay)(nil), "pceapiproto.StopBGPReplay")
	proto.RegisterType((*SessionsRequest)(nil), "pceapiproto.SessionsRequest")
	proto.RegisterType((*Session)(nil), "pceapiproto.Session")
	proto.RegisterType((*SessionsReply)(nil), "pceapiproto.SessionsReply")
	proto.RegisterType((*LSPRequest)(nil), "pceapiproto.LSPRequest")
	proto.RegisterType((*LSP)(nil), "pceapiproto.LSP")
	proto.RegisterType((*LSPReply)(nil), "pceapiproto.LSPReply")
}

func init() { proto.RegisterFile("pceapi.proto", fileDescriptor_614bac86d996c9a3) }

var fileDescriptor_614bac86d996c9a3 = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xdf, 0x8a, 0xd3, 0x4e,
	0x14, 0xc7, 0x77, 0x9a, 0xfe, 0x49, 0x4f, 0xb7, 0xbb, 0xfd, 0x0d, 0xfb, 0xd3, 0xa1, 0x2e, 0xa5,
	0x04, 0x91, 0x82, 0x50, 0x96, 0xf5, 0xd2, 0xab, 0xb6, 0x29, 0xb5, 0x58, 0x35, 0x4c, 0x84, 0x05,
	0xef, 0x62, 0x32, 0x2c, 0x81, 0x69, 0x32, 0x26, 0xd3, 0xc5, 0xbe, 0x89, 0xb7, 0x3e, 0x8a, 0x77,
	0x5e, 0x0a, 0xbe, 0x80, 0xd4, 0x17, 0x91, 0x99, 0x49, 0xd3, 0xc6, 0x55, 0xbc, 0xca, 0x7c, 0x3f,
	0xdf, 0x93, 0x99, 0x73, 0x4e, 0xce, 0x04, 0x4e, 0x45, 0xc8, 0x02, 0x11, 0x8f, 0x45, 0x96, 0xca,
	0x14, 0x77, 0x8c, 0xd2, 0xc2, 0xe9, 0xc1, 0x99, 0x2f, 0x53, 0x31, 0x5d, 0x78, 0x94, 0x7d, 0xd8,
	0xb0, 0x5c, 0x3a, 0xe7, 0xd0, 0x2d, 0x89, 0xe0, 0xc1, 0xd6, 0x79, 0x0a, 0xe7, 0x3e, 0xcb, 0xf3,
	0x38, 0x4d, 0xf2, 0x22, 0x06, 0x13, 0x68, 0x89, 0x30, 0x7c, 0x1d, 0xac, 0x19, 0x41, 0x43, 0x34,
	0x6a, 0xd3, 0xbd, 0x74, 0x3e, 0x23, 0x68, 0x15, 0xd1, 0xf8, 0x0c, 0x6a, 0x4b, 0xb7, 0x08, 0xa8,
	0x2d, 0x5d, 0xdc, 0x07, 0xfb, 0x55, 0x7e, 0x3b, 0x4b, 0x37, 0x89, 0x24, 0xb5, 0x21, 0x1a, 0xd5,
	0x69, 0xa9, 0xf1, 0x05, 0x34, 0x7c, 0x19, 0x48, 0x46, 0xac, 0x21, 0x1a, 0x35, 0xa8, 0x11, 0xea,
	0x9c, 0x20, 0x8a, 0x32, 0x96, 0xe7, 0xa4, 0x6e, 0xce, 0x29, 0x24, 0xbe, 0x84, 0xf6, 0x4b, 0xc6,
	0x44, 0xc0, 0xe3, 0x3b, 0x46, 0x1a, 0x43, 0x34, 0xea, 0xd2, 0x03, 0x50, 0xae, 0xcb, 0x82, 0xe8,
	0x6d, 0xbc, 0x66, 0x19, 0x69, 0x1a, 0xb7, 0x04, 0xce, 0x04, 0xba, 0x87, 0x82, 0x04, 0xdf, 0xe2,
	0x2b, 0xb0, 0xf3, 0x02, 0x10, 0x34, 0xb4, 0x46, 0x9d, 0xeb, 0x8b, 0xf1, 0x51, 0x93, 0xc6, 0x45,
	0x34, 0x2d, 0xa3, 0x9c, 0x27, 0x00, 0x2b, 0xdf, 0xfb, 0x77, 0x3b, 0xbe, 0x58, 0x60, 0xad, 0x7c,
	0x4f, 0x95, 0xee, 0x32, 0xce, 0x6e, 0x55, 0x85, 0x2a, 0xc4, 0xa6, 0xa5, 0xc6, 0x18, 0xea, 0xfe,
	0x36, 0x09, 0x75, 0x4b, 0x6c, 0xaa, 0xd7, 0xf8, 0x01, 0x34, 0x29, 0x5b, 0xa7, 0x77, 0xa6, 0x1f,
	0x36, 0x2d, 0x94, 0x6a, 0xd3, 0x24, 0x5a, 0xc7, 0x89, 0x6e, 0x87, 0x4d, 0x8d, 0x50, 0x3b, 0xbc,
	0x11, 0x2c, 0x2b, 0xfa, 0xa0, 0xd7, 0x8a, 0xe9, 0x84, 0x9a, 0x3a, 0x21, 0xbd, 0xc6, 0x3d, 0xb0,
	0xfc, 0x2c, 0x24, 0x2d, 0x8d, 0xd4, 0x52, 0x11, 0x37, 0x97, 0xc4, 0x36, 0xc4, 0xcd, 0xa5, 0x6a,
	0x9d, 0xcf, 0xe4, 0x46, 0x78, 0x59, 0x9c, 0x92, 0xb6, 0x69, 0x5d, 0x09, 0x54, 0x1d, 0x2f, 0x52,
	0x1e, 0x69, 0x13, 0xb4, 0x59, 0x6a, 0xec, 0xc0, 0xe9, 0x2a, 0x0d, 0x03, 0xee, 0x65, 0xa9, 0x64,
	0xa1, 0x24, 0x1d, 0x9d, 0x62, 0x85, 0xa9, 0x91, 0x98, 0xde, 0x90, 0x53, 0xfd, 0x66, 0x6d, 0x7a,
	0xa3, 0xea, 0xf4, 0x56, 0xbe, 0xb7, 0x74, 0x49, 0x57, 0xb3, 0x42, 0xa9, 0x3a, 0x0d, 0x3e, 0xd3,
	0xb8, 0x51, 0x52, 0x9f, 0x2a, 0x7a, 0x6e, 0xa8, 0x16, 0x78, 0x00, 0x30, 0xff, 0x18, 0xf2, 0x4d,
	0xc4, 0x26, 0xc9, 0x96, 0xf4, 0xb4, 0x75, 0x44, 0x94, 0xbf, 0x4c, 0x4a, 0xff, 0x3f, 0xe3, 0x1f,
	0xc8, 0xb1, 0xcf, 0x39, 0xc1, 0x55, 0x9f, 0x73, 0xe7, 0x0a, 0x6c, 0xfd, 0xad, 0xd5, 0xa4, 0x3c,
	0x86, 0xfa, 0xca, 0xf7, 0xf6, 0x53, 0xd2, 0xab, 0x4c, 0x89, 0x0a, 0xd2, 0xee, 0xf5, 0x77, 0x04,
	0x96, 0x37, 0x9b, 0xe3, 0x25, 0x74, 0x16, 0x4c, 0xee, 0x67, 0x0d, 0x5f, 0xfe, 0x69, 0xa8, 0xf6,
	0x77, 0xaa, 0xdf, 0xff, 0x8b, 0x2b, 0xf8, 0xd6, 0x39, 0xc1, 0xcf, 0xa1, 0xb5, 0x60, 0x52, 0xed,
	0x8e, 0x1f, 0xde, 0x3b, 0xb5, 0xd8, 0xe1, 0xff, 0xfb, 0x86, 0x79, 0xd9, 0x85, 0x56, 0x71, 0xa5,
	0xf1, 0xa3, 0xea, 0x29, 0x95, 0xab, 0xff, 0x7b, 0x0a, 0x95, 0xbf, 0xc0, 0xc9, 0x74, 0xfc, 0x75,
	0x37, 0x40, 0xdf, 0x76, 0x03, 0xf4, 0x63, 0x37, 0x40, 0x9f, 0x7e, 0x0e, 0x4e, 0xa0, 0x2d, 0x42,
	0x66, 0x7e, 0x2a, 0x53, 0xdb, 0x9b, 0xcd, 0xd5, 0x47, 0x4e, 0x3d, 0xf4, 0xae, 0xa1, 0xd1, 0xfb,
	0xa6, 0x7e, 0x3c, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0x62, 0x85, 0x16, 0x0f, 0x7e, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PCEClient is the client API for PCE service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PCEClient interface {
	GetSessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsReply, error)
	GetLSPs(ctx context.Context, in *LSPRequest, opts ...grpc.CallOption) (*LSPReply, error)
	StopBGP(ctx context.Context, in *StopBGPRequest, opts ...grpc.CallOption) (*StopBGPReplay, error)
}

type pCEClient struct {
	cc *grpc.ClientConn
}

func NewPCEClient(cc *grpc.ClientConn) PCEClient {
	return &pCEClient{cc}
}

func (c *pCEClient) GetSessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsReply, error) {
	out := new(SessionsReply)
	err := c.cc.Invoke(ctx, "/pceapiproto.PCE/GetSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEClient) GetLSPs(ctx context.Context, in *LSPRequest, opts ...grpc.CallOption) (*LSPReply, error) {
	out := new(LSPReply)
	err := c.cc.Invoke(ctx, "/pceapiproto.PCE/GetLSPs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCEClient) StopBGP(ctx context.Context, in *StopBGPRequest, opts ...grpc.CallOption) (*StopBGPReplay, error) {
	out := new(StopBGPReplay)
	err := c.cc.Invoke(ctx, "/pceapiproto.PCE/StopBGP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PCEServer is the server API for PCE service.
type PCEServer interface {
	GetSessions(context.Context, *SessionsRequest) (*SessionsReply, error)
	GetLSPs(context.Context, *LSPRequest) (*LSPReply, error)
	StopBGP(context.Context, *StopBGPRequest) (*StopBGPReplay, error)
}

// UnimplementedPCEServer can be embedded to have forward compatible implementations.
type UnimplementedPCEServer struct {
}

func (*UnimplementedPCEServer) GetSessions(ctx context.Context, req *SessionsRequest) (*SessionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessions not implemented")
}
func (*UnimplementedPCEServer) GetLSPs(ctx context.Context, req *LSPRequest) (*LSPReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLSPs not implemented")
}
func (*UnimplementedPCEServer) StopBGP(ctx context.Context, req *StopBGPRequest) (*StopBGPReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopBGP not implemented")
}

func RegisterPCEServer(s *grpc.Server, srv PCEServer) {
	s.RegisterService(&_PCE_serviceDesc, srv)
}

func _PCE_GetSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServer).GetSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pceapiproto.PCE/GetSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServer).GetSessions(ctx, req.(*SessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCE_GetLSPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LSPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServer).GetLSPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pceapiproto.PCE/GetLSPs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServer).GetLSPs(ctx, req.(*LSPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCE_StopBGP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopBGPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCEServer).StopBGP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pceapiproto.PCE/StopBGP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCEServer).StopBGP(ctx, req.(*StopBGPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PCE_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pceapiproto.PCE",
	HandlerType: (*PCEServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSessions",
			Handler:    _PCE_GetSessions_Handler,
		},
		{
			MethodName: "GetLSPs",
			Handler:    _PCE_GetLSPs_Handler,
		},
		{
			MethodName: "StopBGP",
			Handler:    _PCE_StopBGP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pceapi.proto",
}

func (m *StopBGPRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StopBGPRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StopBGPRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *StopBGPReplay) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StopBGPReplay) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StopBGPReplay) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *SessionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SessionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SessionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.PccName) > 0 {
		i -= len(m.PccName)
		copy(dAtA[i:], m.PccName)
		i = encodeVarintPceapi(dAtA, i, uint64(len(m.PccName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Session) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Session) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Session) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.DeadTimer != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.DeadTimer))
		i--
		dAtA[i] = 0x30
	}
	if m.Keepalive != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.Keepalive))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintPceapi(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x22
	}
	if m.State != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x18
	}
	if m.MsgCount != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.MsgCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintPceapi(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SessionsReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SessionsReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SessionsReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Sessions) > 0 {
		for iNdEx := len(m.Sessions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sessions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPceapi(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *LSPRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LSPRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LSPRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.PccName) > 0 {
		i -= len(m.PccName)
		copy(dAtA[i:], m.PccName)
		i = encodeVarintPceapi(dAtA, i, uint64(len(m.PccName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LSP) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LSP) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LSP) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.IncludeAll != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.IncludeAll))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.IncludeAny != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.IncludeAny))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.ExcludeAny != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.ExcludeAny))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.SRPID != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.SRPID))
		i--
		dAtA[i] = 0x78
	}
	if m.LSPID != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.LSPID))
		i--
		dAtA[i] = 0x70
	}
	if m.PLSPID != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.PLSPID))
		i--
		dAtA[i] = 0x68
	}
	if m.BW != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.BW))
		i--
		dAtA[i] = 0x60
	}
	if m.LocalProtect {
		i--
		if m.LocalProtect {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.HoldPrio != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.HoldPrio))
		i--
		dAtA[i] = 0x50
	}
	if m.SetupPrio != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.SetupPrio))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Dst) > 0 {
		i -= len(m.Dst)
		copy(dAtA[i:], m.Dst)
		i = encodeVarintPceapi(dAtA, i, uint64(len(m.Dst)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Src) > 0 {
		i -= len(m.Src)
		copy(dAtA[i:], m.Src)
		i = encodeVarintPceapi(dAtA, i, uint64(len(m.Src)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPceapi(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x32
	}
	if m.Oper != 0 {
		i = encodeVarintPceapi(dAtA, i, uint64(m.Oper))
		i--
		dAtA[i] = 0x28
	}
	if m.Admin {
		i--
		if m.Admin {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Remove {
		i--
		if m.Remove {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Sync {
		i--
		if m.Sync {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Delegate {
		i--
		if m.Delegate {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LSPReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LSPReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LSPReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.LSPs) > 0 {
		for iNdEx := len(m.LSPs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LSPs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPceapi(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintPceapi(dAtA []byte, offset int, v uint64) int {
	offset -= sovPceapi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StopBGPRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StopBGPReplay) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SessionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PccName)
	if l > 0 {
		n += 1 + l + sovPceapi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Session) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovPceapi(uint64(l))
	}
	if m.MsgCount != 0 {
		n += 1 + sovPceapi(uint64(m.MsgCount))
	}
	if m.State != 0 {
		n += 1 + sovPceapi(uint64(m.State))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovPceapi(uint64(l))
	}
	if m.Keepalive != 0 {
		n += 1 + sovPceapi(uint64(m.Keepalive))
	}
	if m.DeadTimer != 0 {
		n += 1 + sovPceapi(uint64(m.DeadTimer))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SessionsReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Sessions) > 0 {
		for _, e := range m.Sessions {
			l = e.Size()
			n += 1 + l + sovPceapi(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *LSPRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PccName)
	if l > 0 {
		n += 1 + l + sovPceapi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *LSP) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Delegate {
		n += 2
	}
	if m.Sync {
		n += 2
	}
	if m.Remove {
		n += 2
	}
	if m.Admin {
		n += 2
	}
	if m.Oper != 0 {
		n += 1 + sovPceapi(uint64(m.Oper))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPceapi(uint64(l))
	}
	l = len(m.Src)
	if l > 0 {
		n += 1 + l + sovPceapi(uint64(l))
	}
	l = len(m.Dst)
	if l > 0 {
		n += 1 + l + sovPceapi(uint64(l))
	}
	if m.SetupPrio != 0 {
		n += 1 + sovPceapi(uint64(m.SetupPrio))
	}
	if m.HoldPrio != 0 {
		n += 1 + sovPceapi(uint64(m.HoldPrio))
	}
	if m.LocalProtect {
		n += 2
	}
	if m.BW != 0 {
		n += 1 + sovPceapi(uint64(m.BW))
	}
	if m.PLSPID != 0 {
		n += 1 + sovPceapi(uint64(m.PLSPID))
	}
	if m.LSPID != 0 {
		n += 1 + sovPceapi(uint64(m.LSPID))
	}
	if m.SRPID != 0 {
		n += 1 + sovPceapi(uint64(m.SRPID))
	}
	if m.ExcludeAny != 0 {
		n += 2 + sovPceapi(uint64(m.ExcludeAny))
	}
	if m.IncludeAny != 0 {
		n += 2 + sovPceapi(uint64(m.IncludeAny))
	}
	if m.IncludeAll != 0 {
		n += 2 + sovPceapi(uint64(m.IncludeAll))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *LSPReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.LSPs) > 0 {
		for _, e := range m.LSPs {
			l = e.Size()
			n += 1 + l + sovPceapi(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovPceapi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPceapi(x uint64) (n int) {
	return sovPceapi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StopBGPRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPceapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StopBGPRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StopBGPRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPceapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPceapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StopBGPReplay) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPceapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StopBGPReplay: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StopBGPReplay: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPceapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPceapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SessionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPceapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SessionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SessionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PccName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPceapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPceapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PccName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPceapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPceapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Session) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPceapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Session: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Session: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPceapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPceapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgCount", wireType)
			}
			m.MsgCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPceapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPceapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keepalive", wireType)
			}
			m.Keepalive = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Keepalive |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeadTimer", wireType)
			}
			m.DeadTimer = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeadTimer |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPceapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPceapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SessionsReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPceapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SessionsReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SessionsReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sessions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPceapi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPceapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sessions = append(m.Sessions, &Session{})
			if err := m.Sessions[len(m.Sessions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPceapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPceapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LSPRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPceapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LSPRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LSPRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PccName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPceapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPceapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PccName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPceapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPceapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LSP) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPceapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LSP: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LSP: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegate", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Delegate = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sync", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Sync = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Remove", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Remove = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Admin = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Oper", wireType)
			}
			m.Oper = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Oper |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPceapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPceapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Src", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPceapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPceapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Src = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dst", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPceapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPceapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dst = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetupPrio", wireType)
			}
			m.SetupPrio = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SetupPrio |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HoldPrio", wireType)
			}
			m.HoldPrio = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HoldPrio |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalProtect", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LocalProtect = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BW", wireType)
			}
			m.BW = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BW |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PLSPID", wireType)
			}
			m.PLSPID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PLSPID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LSPID", wireType)
			}
			m.LSPID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LSPID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SRPID", wireType)
			}
			m.SRPID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SRPID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExcludeAny", wireType)
			}
			m.ExcludeAny = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExcludeAny |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncludeAny", wireType)
			}
			m.IncludeAny = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IncludeAny |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncludeAll", wireType)
			}
			m.IncludeAll = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IncludeAll |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPceapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPceapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LSPReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPceapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LSPReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LSPReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LSPs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPceapi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPceapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LSPs = append(m.LSPs, &LSP{})
			if err := m.LSPs[len(m.LSPs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPceapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPceapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPceapi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPceapi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPceapi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPceapi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPceapi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPceapi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPceapi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPceapi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPceapi = fmt.Errorf("proto: unexpected end of group")
)
